### ISSUE TITLE
OS 설치가 되지 않습니다.

### ISSUE THREAD

**Issue by ipari** [gigagenie/ai-makers-kit#3]
라즈베리파이3 B+에 https://gigagenie.ai 에서 받은 이미지로 OS를 설치하려고 하는데, 전원을 연결하면 화면에 동그란 그라데이션 창만 나오고 더 이상 진행이 되지 않습니다. 혹시나 SD카드에 잘못 구워졌나 해서 3번 포맷하고 다시 구워보기도 했지만 증상은 동일했습니다. 같은 SD 카드와 기기로 Raspbian OS 설치는 잘 되는 거 보면 기기의 문제는 아닌 것 같습니다.

**Comment by cmlee** [comment]
현재 AI Makers Kit은 RASPBERRY PI 3 MODEL B 만 지원합니다.
문의사항은 [gigagenie.ai > Support > 개발자 포럼](https://gigagenie.ai/support/qna)을 이용해주세요.
