### ISSUE TITLE
AI Makers Kit 설치 후 태스크바 사라짐

### ISSUE THREAD

**Issue by ipari** [gigagenie/ai-makers-kit#4]
라즈베리파이 3 B+에 Raspbian OS (2018-06-27)을 설치하고 AI Makers Kit 드라이버를 설치하였습니다. `aimk-install.sh` 를 실행하고 재부팅할 때 까지는 괜찮으나, 이어서 `after-install.sh` 를 실행하고 재부팅하면 태스크바가 사라지는 현상이 발생합니다. 정확한 증상은 부팅 후에 태스크바가 몇 번 깜빡이다가 사라지는 것입니다. 라즈베리파이에서 태스크바 사라지는 현상에 대한 해결법을 여러가지 시도해보았으나 증상이 해결되지는 않았습니다.

아래 명령어를 치면, 이런 에러 메시지가 나옵니다.

```
$ lxpanel --profile LXDE-pi

** (lxpanel:1927): WARNING **: volumealsa: Couldn't attach mixer -looking for another valid device
** (lxpanel:1927): WARNING **: volumealsa: Default ALSA device not valid - resetting to internal
** (lxpanel:1927): WARNING **: volumealsa: Internal device not available - looking for first valid ALSA device
** (lxpanel:1927): WARNING **: volumealsa: No ALSA devices found
Segnentation fault
```

**Comment by cmlee** [comment]
현재 AI Makers Kit은 RASPBERRY PI 3 MODEL B 만 지원합니다.
문의사항은 [gigagenie.ai > Support > 개발자 포럼](https://gigagenie.ai/support/qna)을 이용해주세요.
